site_name: KubeVirt User-Guide
docs_dir: docs/
repo_url: https://github.com/kubevirt/user-guide/
site_url: https://KubeVirt.io
repo_name: GitHub
use_directory_urls: false

theme:
    name: material
    highlightjs: true
    custom_dir: branding/
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s
